language: android

android:
  components:
    - build-tools-24.0.3
    - android-24
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew checkstyle build